Repository FACN4/StudentProject-WeCook, pull requests merged in 2018-09, with the labels that each got.

#49 Adds code owners to repo
  CODEOWNERS.md
Labels: awaiting-review, chore

#90 fixed typo from old methodology, minor
  client/src/pages/MealsListPage/MealsListPage.js
Labels: awaiting-review

#92 Added margin to allow users to see all content #79
  client/src/components/MealCard/MealCard.js
  client/src/components/MoneyButton/MoneyButton.js
  client/src/components/MoneyButton/MoneyButton.style.js
Labels: awaiting-review

#65 Review info
  README.md
  client/src/actions/actionTypes.js
  client/src/actions/getMealReviews.js
  client/src/pages/MealPage/MealPage.js
  client/src/pages/MealPage/sections/MealInfo/MealInfo.js
  client/src/pages/MealPage/sections/MealReviews/MealReviews.js
  client/src/reducers/getMealInfoReducer.js
  client/src/reducers/getMealListReducer.js
  client/src/reducers/getMealReviewsReducer.js
  client/src/reducers/index.js
  server/controllers/index.js
  server/controllers/mealReviews.js
  server/database/cook_filler_data.sql
  server/database/getQueries/getMealCard.js
  server/database/getQueries/getMealReviews.js
  server/database/getQueries/index.js
  testing/database_tests.js
  testing/testPresetData.js
Labels: awaiting-review

#96 React persist
  .babelrc
  client/src/components/Loading/Loading.js
  client/src/components/Loading/Loading.style.js
  client/src/components/index.js
  client/src/index.js
  client/src/pages/MealPage/sections/MealInfo/MealInfo.js
  client/src/store.js
  package.json
Labels: awaiting-review

#97 Basket Data & MoneyBar #28
  client/src/actions/actionTypes.js
  client/src/actions/addToBasket.js
  client/src/actions/removeBasketItem.js
  client/src/components/MealCard/MealCard.js
  client/src/components/MoneyButton/MoneyButton.js
  client/src/pages/BasketPage/BasketPage.js
  client/src/pages/MealPage/MealPage.js
  client/src/pages/MealPage/sections/MealInfo/MealInfo.js
  client/src/pages/MealsListPage/MealsListPage.js
  client/src/reducers/addBasketReducer.js
  client/src/reducers/basketReducer.js
  client/src/reducers/index.js
Labels: awaiting-review

#95 fixes in cookMealInfo
  client/src/actions/actionTypes.js
  client/src/actions/getMealCookInfo.js
  client/src/pages/MealPage/MealPage.js
  client/src/pages/MealPage/sections/MealCookInfo/MealCookInfo.js
  client/src/pages/MealPage/sections/MealReviews/MealReviews.js
  client/src/reducers/getMealCookInfoReducer.js
  client/src/reducers/index.js
  package-lock.json
  server/app.js
  server/controllers/index.js
  server/controllers/mealCookInfo.js
  server/database/getQueries/getMealCookInfo.js
  server/database/getQueries/index.js
  server/database/getQueries/mealReviews.js
  server/index.js
  testing/database_tests.js
Labels: awaiting-review, changes made

#99 Meal Page Styling #68
  client/src/pages/MealPage/MealPage.js
  client/src/pages/MealPage/MealPageStyle.js
  client/src/pages/MealPage/sections/MealCookInfo/MealCookInfo.js
  client/src/pages/MealPage/sections/MealCookInfo/MealCookInfo.style.js
  client/src/pages/MealPage/sections/MealInfo/MealInfo.js
  client/src/pages/MealPage/sections/MealInfo/MealInfo.style.js
  client/src/pages/MealPage/sections/MealReviews/MealReview.style.js
  client/src/pages/MealPage/sections/MealReviews/MealReviews.js
Labels: awaiting-review

#106 Global style #103
  client/src/App.style.js
  client/src/assets/global.css
  client/src/index.js
Labels: awaiting-review

#105 Stripe integration #76
  .babelrc
  client/src/Router.js
  client/src/index.html
  client/src/pages/CheckoutPage/CheckoutPage.js
  client/src/pages/CheckoutPage/sections/CheckoutForm/CheckoutForm.js
  client/src/pages/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/stripeCharge.js
  webpack.config.js
Labels: awaiting-review

#107 Thank you page #78
  client/src/pages/CheckoutPage/sections/CheckoutForm/CheckoutForm.js
  client/src/pages/CheckoutPage/sections/ThankYou/ThankYou.js
  client/src/pages/CheckoutPage/sections/ThankYou/ThankYou.style.js
Labels: awaiting-review

#114 Order Total now in checkout bar #110
  client/src/components/MoneyButton/MoneyButton.js
  client/src/pages/BasketPage/BasketPage.js
  client/src/utils/formatingLogic.js
  client/src/utils/priceFormat.js
Labels: awaiting-review

#98 Home page
  client/.eslintrc.json
  client/src/App.style.js
  client/src/Router.js
  client/src/assets/logoDarkBlue.svg
  client/src/components/DatePicker/DatePicker.js
  client/src/components/Footer/Footer.js
  client/src/components/Footer/Footer.style.js
  client/src/components/Footer/FooterWrapper.js
  client/src/components/index.js
  client/src/pages/BasketPage/BasketPage.js
  client/src/pages/HomePage/HomePage.js
  client/src/pages/HomePage/HomePage.style.js
  client/src/pages/HomePage/sections/AboutTheCompany/AboutTheCompany.js
  client/src/pages/HomePage/sections/HomeHeader/HomeHeader.js
  client/src/pages/HomePage/sections/HomeHeader/HomeHeader.style.js
  client/src/pages/HomePage/sections/MealSearchForm/MealSearchForm.css
  client/src/pages/HomePage/sections/MealSearchForm/MealSearchForm.js
  client/src/pages/HomePage/sections/MealSearchForm/MealSearchForm.style.js
  client/src/pages/MealPage/MealPage.js
  client/src/pages/MealsListPage/MealsListPage.js
  client/src/pages/index.js
  client/src/reducers/index.js
  client/src/themes/buttons.style.js
  package-lock.json
  package.json
  webpack.config.js
Labels: awaiting-review

#116 Add stars
  client/src/components/Stars/Stars.style.js
  client/src/pages/MealPage/MealPage.js
  client/src/pages/MealPage/sections/MealCookInfo/MealCookInfo.js
  client/src/pages/MealPage/sections/MealCookInfo/MealCookInfo.style.js
  client/src/pages/MealPage/sections/MealReviews/MealReviews.js
  client/src/pages/MealsListPage/MealsListPage.js
  client/src/utils/starsStyleHelper.js
  server/database/getQueries/getMealCard.js
  server/database/getQueries/getMealCookInfo.js
  server/database/getQueries/getMealList.js
  testing/testPresetData.js
Labels: awaiting-review

#104 Login+register
  client/src/Router.js
  client/src/actions/actionTypes.js
  client/src/actions/userLogin.js
  client/src/actions/userLogout.js
  client/src/actions/userRegister.js
  client/src/components/Header/Header.js
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/RegisterPage/RegisterPage.js
  client/src/pages/index.js
  client/src/reducers/index.js
  client/src/reducers/userStatusReducer.js
  client/src/store.js
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/userLogin.js
  server/controllers/userLogout.js
  server/controllers/userRegister.js
  server/database/getQueries/getHashedPass.js
  server/index.js
  server/utils/hashPassword.js
  server/utils/jwtHelper.js
Labels: awaiting-review

#121 Homepage labels #119
  client/src/pages/HomePage/sections/MealSearchForm/MealSearchForm.js
  client/src/pages/HomePage/sections/MealSearchForm/MealSearchForm.style.js
Labels: awaiting-review

#143 Basket work
  client/src/actions/actionTypes.js
  client/src/actions/editBasketItem.js
  client/src/components/Header/Header.js
  client/src/pages/BasketPage/BasketPage.js
  client/src/reducers/basketReducer.js
  client/src/store.js
Labels: awaiting-review

#135 Meal List Page
  client/src/pages/MealsListPage/MealsListPage.js
  client/src/pages/MealsListPage/MealsListPage.style.js
Labels: awaiting-review

#120 Body Padding to all pages #100
  client/src/components/Footer/Footer.style.js
  client/src/components/Header/Header.style.js
  client/src/components/MoneyButton/MoneyButton.style.js
  client/src/pages/BasketPage/BasketPage.js
  client/src/pages/BasketPage/BasketPage.style.js
  client/src/pages/CheckoutPage/sections/CheckoutForm/CheckoutForm.js
  client/src/pages/CheckoutPage/sections/CheckoutForm/CheckoutForm.style.js
  client/src/pages/CheckoutPage/sections/ThankYou/ThankYou.js
  client/src/pages/CheckoutPage/sections/ThankYou/ThankYou.style.js
  client/src/pages/MealPage/MealPage.js
  client/src/pages/MealPage/MealPage.style.js
  client/src/pages/MealPage/sections/MealInfo/MealInfo.js
  client/src/pages/MealsListPage/MealsListPage.js
  client/src/pages/MealsListPage/MealsListPage.style.js
  client/src/themes/weCookv1.js
Labels: awaiting-review
